// packages/useq/src/components/knob.tsx
import { mapUnaryTo } from "beams/ax/number-utils";
import { KnobFrame } from "beams/mo-solid/components/knob-frame";
import { mergeProps } from "solid-js";

export function KnobView(props: { value: number; min: number; max: number }) {
  const vm = {
    tickAngel() {
      const { value, min, max } = props;
      const normValue = (value - min) / (max - min);
      const halfRange = 135;
      const angle = mapUnaryTo(normValue, -halfRange, halfRange);
      return angle;
    },
  };
  return (
    <div class="border border-[#444] w-[30px] h-[30px] rounded-full bg-[#aaa]">
      <div
        class="w-full h-full flex justify-center"
        style={{
          transform: `rotate(${vm.tickAngel()}deg)`,
        }}
      >
        <div class="w-[1px] h-[10px] bg-[#444]" />
      </div>
    </div>
  );
}

export function Knob(inputProps: {
  value: number;
  min?: number;
  max?: number;
  step?: number;
  onChange: (value: number) => void;
}) {
  const props = mergeProps({ min: 0, max: 1, step: 0.01 }, inputProps);
  return (
    <KnobFrame
      value={props.value}
      min={props.min}
      max={props.max}
      step={props.step}
      onChange={props.onChange}
    >
      <KnobView value={props.value} min={props.min} max={props.max} />
    </KnobFrame>
  );
}

// packages/drum-machines/techno-beat-machine/src/ui/components/knob.tsx
import { qu } from "@/ui/common/css-realm";
import { KnobFrame } from "@/ui/components/knob-frame";
import { linearInterpolate } from "@/utils/helpers";

export const Knob = ({
  value,
  onChange,
  min = 0,
  max = 1,
  step = 0.01,
  onClick,
  disabled,
}: {
  value: number;
  onChange: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  onClick?: () => void;
  disabled?: boolean;
}) => {
  const tickAngle = linearInterpolate(value, min, max, -135, 135);
  return (
    <KnobFrame
      value={value}
      min={min}
      max={max}
      step={step}
      onChange={onChange}
      onClick={onClick}
      dragDisabled={disabled}
    >
      <div
        sx={qu.wh(36, 36).rounded("100%").relative().bg("#aaa")}
        style={{ opacity: disabled ? 0.5 : 1 }}
      >
        <div
          sx={qu.full().flexVA()}
          style={{ transform: `rotate(${tickAngle}deg)` }}
        >
          <div sx={qu.wh(2, 10).bg("#fff")} />
        </div>
      </div>
    </KnobFrame>
  );
};
