// specbar/src/components/knob-frame.tsx
import { clampValue } from "beams/ax/number-utils";
import { startDragSession } from "beams/ax-ui/drag-session";
import { ReactNode } from "react";

export function KnobFrame(props: {
  value: number;
  min: number;
  max: number;
  step: number;
  children: ReactNode;
  onChange: (value: number) => void;
  dragRange?: number;
}) {
  const handlePointerDown = (e0: React.PointerEvent) => {
    const min = props.min;
    const max = props.max;
    const step = props.step;
    const dragRange = props.dragRange ?? 100;

    const originalValue = props.value;
    startDragSession(e0.nativeEvent, {
      onMove(e) {
        const delta =
          -(e.position.y - e.originalPosition.y) / (dragRange / (max - min));
        let newValue = originalValue + delta;
        if (step > 0) {
          newValue = Math.round(newValue / step) * step;
        }
        newValue = clampValue(newValue, min, max);
        props.onChange(newValue);
      },
    });
  };
  return (
    <div onPointerDown={handlePointerDown} className="cursor-pointer">
      {props.children}
    </div>
  );
}

// useq/src/components/knob-frame.tsx
import { clampValue } from "@beam/ax/number-utils";
import { startDragSession } from "@beam/ax-ui/drag-session";
import { JSXElement } from "solid-js";

export function KnobFrame(props: {
  value: number;
  min: number;
  max: number;
  step: number;
  children: JSXElement;
  onChange: (value: number) => void;
  dragRange?: number;
}) {
  const handlePointerDown = (e0: PointerEvent) => {
    const min = props.min;
    const max = props.max;
    const step = props.step;
    const dragRange = props.dragRange ?? 100;

    const originalValue = props.value;
    startDragSession(e0, {
      onMove(e) {
        const delta =
          -(e.position.y - e.originalPosition.y) / (dragRange / (max - min));
        let newValue = originalValue + delta;
        if (step > 0) {
          newValue = Math.round(newValue / step) * step;
        }
        newValue = clampValue(newValue, min, max);
        props.onChange(newValue);
      },
    });
  };
  return (
    <div onPointerDown={handlePointerDown} class="cursor-pointer">
      {props.children}
    </div>
  );
}
