// specbar/src/components/knob-frame.tsx
import { clampValue } from "beams/ax/number-utils";
import { startDragSession } from "beams/ax-ui/drag-session";
import { ReactNode } from "react";

export function KnobFrame(props: {
  value: number;
  min: number;
  max: number;
  step: number;
  children: ReactNode;
  onChange: (value: number) => void;
  dragRange?: number;
}) {
  const handlePointerDown = (e0: React.PointerEvent) => {
    const min = props.min;
    const max = props.max;
    const step = props.step;
    const dragRange = props.dragRange ?? 100;

    const originalValue = props.value;
    startDragSession(e0.nativeEvent, {
      onMove(e) {
        const delta =
          -(e.position.y - e.originalPosition.y) / (dragRange / (max - min));
        let newValue = originalValue + delta;
        if (step > 0) {
          newValue = Math.round(newValue / step) * step;
        }
        newValue = clampValue(newValue, min, max);
        props.onChange(newValue);
      },
    });
  };
  return (
    <div onPointerDown={handlePointerDown} className="cursor-pointer">
      {props.children}
    </div>
  );
}

// packages/synthesizers/radiant-rs/src/components/knob-frame.svelte
<script lang="ts">
  import { startDragSession } from "@lib/mu2609/utils/drag-session";
  import { clampValue } from "@lib/mu2609/utils/helpers";
  import type { Snippet } from "svelte";

  type Props = {
    className?: string;
    value: number;
    min?: number;
    max?: number;
    step?: number;
    onchange?: (value: number) => void;
    dragRange?: number;
    children: Snippet;
  };

  let {
    className,
    value,
    min = 0,
    max = 1,
    step = 0.01,
    onchange = () => {},
    dragRange = 100,
    children,
  }: Props = $props();

  function handlePointerDown(e0: PointerEvent) {
    const originalValue = value;
    startDragSession(e0, {
      onMove(e) {
        const deltaY = e.position.y - e.originalPosition.y;
        let newValue = clampValue(
          originalValue - (deltaY * (max - min)) / dragRange,
          min,
          max,
        );
        if (step > 0) {
          newValue = Math.round(newValue / step) * step;
        }
        onchange(newValue);
      },
    });
  }
</script>

<div
  onpointerdown={handlePointerDown}
  class={className}
  style="cursor: pointer;"
>
  {@render children()}
</div>
