// lseq1/src/components/number-slider-box.tsx
import { KnobFrame } from "./knob-frame";

export function NumberSliderBoxView(props: {
  value: number;
  fracDigits?: number;
  displayText?: string;
}) {
  return (
    <div className="border border-[#444] bg-[#fff] w-[60px] h-[34px] flex-c">
      {props.displayText ?? props.value.toFixed(props.fracDigits ?? 2)}
    </div>
  );
}

export function FeNumberSliderBox({
  label,
  value,
  min = 0,
  max = 100,
  step = 1,
  fracDigits = 0,
  displayText,
  onChange,
}: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  fracDigits?: number;
  displayText?: string;
  onChange: (value: number) => void;
}) {
  return (
    <div className="flex-vc">
      {label && <div className="text-[14px]">{label}</div>}
      <KnobFrame
        value={value}
        min={min}
        max={max}
        step={step}
        onChange={onChange}
      >
        <NumberSliderBoxView
          value={value}
          fracDigits={fracDigits}
          displayText={displayText}
        />
      </KnobFrame>
    </div>
  );
}

// proto-engine-ptm-osc/src/components/number-slider-box.tsx
import { JSXElement, mergeProps } from "solid-js";
import { KnobFrame } from "./knob-frame";
import { ParameterRow } from "./parameter-row";

export function NumberSliderBoxView(props: {
  value: number;
  fracDigits?: number;
}) {
  return (
    <div class="border border-[#444] flex-c">
      {props.value.toFixed(props.fracDigits ?? 2)}
    </div>
  );
}

export function FeNumberSliderBox(inputProps: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  fracDigits?: number;
  onChange: (value: number) => void;
}): JSXElement {
  const props = mergeProps(
    { min: 0, max: 1, step: 0.01, fracDigits: 2 },
    inputProps,
  );
  return (
    <ParameterRow label={props.label}>
      <KnobFrame
        value={props.value}
        min={props.min}
        max={props.max}
        step={props.step}
        onChange={props.onChange}
      >
        <NumberSliderBoxView
          value={props.value}
          fracDigits={props.fracDigits}
        />
      </KnobFrame>
    </ParameterRow>
  );
}
